name: Release on Tag

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up latest Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install UPX
        run: |
          curl -LO https://github.com/upx/upx/releases/download/v5.0.1/upx-5.0.1-amd64_linux.tar.xz
          tar -xf upx-5.0.1-amd64_linux.tar.xz
          sudo mv upx-5.0.1-amd64_linux/upx /usr/local/bin/
          upx --version

      - name: Build with Makefile
        run: make build

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
